---
title: "Day_1_Basic_Plot"
author: "Bashir,I. (2022)"
date: "3/5/2022"
output:
  pdf_document: default
  html_document: default
---

# Basic Plotting

1- Plot

```{r}
data("iris")
plot(iris$Sepal.Length, iris$Sepal.Width)
```

2- histogram

```{r}
hist(iris$Sepal.Length)
```

3- boxplot

```{r}
boxplot(Sepal.Length ~ Species, data = iris)
```

4- image graph

```{r}
x <- matrix(1:120, 12, 10)
x
image(x)
```

5- strip chart

```{r}
stripchart(iris$Sepal.Length)
```

6- qqnormplot

```{r}
qqnorm(iris$Sepal.Length)
```

intermediate plotting

1- scatter plot

```{r}
plot(iris$Sepal.Length, iris$Sepal.Width, xlab="sepal length", ylab = "sepal width", main = "IRIS Scatter Plot")
```

2- Correlation plot

```{r}
plot(iris)
```

Corr plot

```{r}
library(corrplot)
# first calculate the correlation
c <- cor(iris[,-5])
corrplot(c)
```

another diverse dataset

```{r}
car <- cor(mtcars)
corrplot(car)
```

Number format

```{r}
corrplot(car, method = "number")
```

Upper plot

```{r}
corrplot(car, method = "number", type= "upper")
```

Upper plot

```{r}
corrplot(car, method = "number", type= "lower")
```

square

```{r}
corrplot(car, method = "square", type= "lower")
```

Ellipsis

```{r}
corrplot(car, method = "ellipse", type= "lower")
```

Order of corrlation

```{r}
corrplot(car, method = "square", type= "lower", order = 'AOE')
```

Mixed corrplot

```{r}
corrplot.mixed(c)
corrplot.mixed(c, lower = "number", upper = "pie",  order = 'AOE')
```

Clusstering

```{r}
corrplot(car,  order = 'hclust', addrect = 2)
```

for more information visit this link <https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html>

Another Method

```{r}
library(PerformanceAnalytics)
chart.Correlation(car, method = "pearson", histogram = TRUE)
```

Alos see this link: <https://r-coder.com/correlation-plot-r/>
